### PR TITLE
Without slinky.web.html.placeholder

### PR DESCRIPTION
**Pull request by mcallisto**

### CODE REVIEW

**Comment by oyvindberg** [comment]
Nice! If you feel like it it would be even better to remove the dependency on slinky-web for the react-native project. Otherwise LGTM

**Comment by mcallisto** [comment]
> If you feel like it it would be even better to remove the dependency on slinky-web for the react-native project.

Ok, I tried

**Comment by oyvindberg** [comment]
That looks like a good way of doing it. It's currently missing the scalajs-dom dependency for slinky native, and slinky native is declared two times for react-native. If you can fix up that we're good here :)

**Comment by mcallisto** [comment]
> If you can fix up that we're good here :)

Done!

**Comment by oyvindberg** [comment]
Thanks!

**Pull request merged**
