### PR TITLE
Correct i18next errors

### PR DESCRIPTION
**Pull request by mcallisto**
The current demo was not fully working, throwing the following console errors:

+ `react-i18next:: Trans: the passed in value is invalid - seems you passed in a variable like {number} - please pass in variables for interpolation as full objects like {{number}}. 12 react-i18n-opt-bundle.js:30:14750`
+ `i18next::translator: missingKey de translations <1>xxx</1> <1>xxx</1>`

Now it is correct, even if I have not been able to trace the original demo, if there was one, so I am not totally sure about what was the intended result.

### CODE REVIEW

**Comment by mcallisto** [comment]
I went back to status `Draft`.

I wanted to make it more meaningful, but I am struggling to get [Plurals](https://www.i18next.com/translation-function/plurals), [Context](https://www.i18next.com/translation-function/context) and [Interpolation](https://www.i18next.com/translation-function/interpolation) working...

**Comment by mcallisto** [comment]
https://github.com/ScalablyTyped/SlinkyDemos/pull/26/commits/32bbe73900a862d62859b5cfdbc82df65d9c4615 otherwise:
`Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app. react-dom.development.js:88:30`

**Review by oyvindberg — APPROVED** [review]
Cool, thanks!

Merge when you're happy with it :)

**Comment by mcallisto** [comment]
> Cool, thanks!
> 
> Merge when you're happy with it :)

Thank you! Merging now, it is a small step forward anyway.

I will try opening an issue for remaining unsolved use cases.

**Pull request merged**
