### PR TITLE
fix(material-ui) : render wrong when collapsing the drawer

### PR DESCRIPTION
**Pull request by mvillafuertem**
There is one outstanding issue with icon notifications because padding right is not applied correctly, I think that it is because we use hook state, maybe using Stateful Component this works.

Screenshot 2020-06-06 at 19 50 59

### CODE REVIEW

**Comment by oyvindberg** [comment]
Looks perfect, thanks!

I gave you write access to the repo, so I think you can merge yourself now, whenever you think it's ready?

**Review by oyvindberg — APPROVED** [review]

**Comment by oyvindberg** [comment]
Oh yeah, if you could run `material-ui/dist` in sbt and check in the changes on `docs/` that would be great, I'll update the readme with links to the deployed demos

**Comment by mvillafuertem** [comment]
Now I'm trying to change style color, but I don't know where is the problem. I have created a simple button to test this behaviour.

```scala 

package demo.button

import org.scalajs.dom
import slinky.core._
import slinky.core.annotations.react
import slinky.web.ReactDOM
import typings.materialUiCore.colorsMod.{blue, pink}
import typings.materialUiCore.createMuiThemeMod.{Theme, ThemeOptions}
import typings.materialUiCore.createPaletteMod.{ColorPartial, PaletteOptions}
import typings.materialUiCore.createTypographyMod.TypographyOptions
import typings.materialUiCore.materialUiCoreStrings.contained
import typings.materialUiCore.mod.PropTypes.Color
import typings.materialUiCore.{stylesMod, components => Mui}
import typings.materialUiStyles.components.ThemeProvider
import typings.std.global.window

object Button extends App {

  val theme: Theme = stylesMod
    .createMuiTheme(
      ThemeOptions()
        .setTypography(TypographyOptions().setUseNextVariants(true))
        .setPalette(PaletteOptions()
          .setPrimary(ColorPartial().combineWith(blue))
          .setSecondary(ColorPartial().combineWith(pink))
        ))

  println(theme.palette.primary.main)

  ReactDOM.render(
    ThemeProvider(theme)(StyledButtonDemo()),
    dom.document.getElementById("container")
  )
}

// https://v3.material-ui.com/customization/themes/#withtheme-component-component
@react
object StyledButtonDemo {

  import typings.materialUiStyles.mod.withTheme

  type Props = Unit

  val component: FunctionalComponent[Props] = FunctionalComponent[Props] {
    case () =>

      val styleInjector = withTheme()

      Mui.Button
        .withComponent(c => styleInjector(c))
        .color(Color.primary)
        .variant(contained)
        .onClick(_ => window.alert("clicked"))("using withTheme")

  }

}



```

**Comment by mvillafuertem** [comment]
Forget it, It is my mistake. I was using ThemeProvider instead of MuiThemeProvider. Now all looks perfect.

**Pull request merged**
