### PR TITLE
feature(material-ui) : add dashboard layout example

### PR DESCRIPTION
**Pull request by mvillafuertem**
Hi, I'm trying to converter this layout

https://v3.material-ui.com/getting-started/page-layout-examples/dashboard/

In some situations I don't know how make the conversion. Could you help me?

Thanks

### CODE REVIEW

**Comment by oyvindberg** [comment]
Cool, thanks for opening the PR :) 

I'm back a day or two, will have a look after that. Can you comment what is not working?

**Comment by oyvindberg** [comment]
I had a quick look now. This will be a great sample of how to use material-ui. I think there will be no point in keeping the existing code after we add this, so feel free to just call it material-ui and delete the old stuff.

Just tell what the pain points are, and I'll see how we can make it better :)

**Comment by mvillafuertem** [comment]
I have added in the pain points TODOs.

**Comment by oyvindberg** [comment]
Thanks for the todos! I ran quickly through them now in https://github.com/ScalablyTyped/SlinkyDemos/tree/pull/15

Thre are some at least some obvious things we can fix in the conversion, will get back to you with details in some days

**Comment by oyvindberg** [comment]
First fixes: 
- https://github.com/ScalablyTyped/Converter/pull/161
- https://github.com/ScalablyTyped/Converter/pull/160

**Comment by oyvindberg** [comment]
Prototype of material styling facade in https://github.com/ScalablyTyped/SlinkyDemos/commit/1dcb3de49d66b899e4a18a934f1364ed243baddf (same branch as before)

**Comment by oyvindberg** [comment]
I force-pushed over my branch now. It's starting to look decent, isnt it? https://github.com/ScalablyTyped/SlinkyDemos/blob/pull/15/material-ui/src/main/scala/demo/dashboard/Dashboard.scala

**Comment by mvillafuertem** [comment]
it looks really great! 👌

**Comment by mvillafuertem** [comment]
I have added another layout, maybe this is interesting for users. 
Is there a way to test the application? Any suggestion?

**Comment by oyvindberg** [comment]
Another layout is great!

I'll release a beta14 within a day or two with the necessary fixes, after that you can pull my branch again and we're almost ready here.

Two outstanding things:
- now there are like three demos in one, which I dont mind given how slow it is to get started. we should probably to a minimalistic router thing to choose between them
- There is one outstanding issue where things render wrong when collapsing the drawer, but it wasnt obvious to me what the problem was

**Comment by oyvindberg** [comment]
This works beautifully now. I took some liberties in moving the routing up and out and separating the demos by route. I also just released beta 14 so I'll go ahead and merge everything now.

If you want to do mere here feel free to open more PRs. Thanks again for an awesome PR, I think this really shows how far ScalablyTyped and slinky has come!

**Comment by mvillafuertem** [comment]
Thanks to you for this awesome converter!

**Pull request merged**
