### PR TITLE
feature(material-ui) : add login layout

### PR DESCRIPTION
**Pull request by mvillafuertem**
Hi again, I would like to add another more complex login layout, but I have problems with svg files. Could you help me? Thanks!

### CODE REVIEW

**Comment by oyvindberg** [comment]
Hi again

This worked on my machine:
1) Move `google.svg` to `material-ui/src/main/js`
2) Change to  `@JSImport("./google.svg", JSImport.Default)`

in `custom.webpack.config` you can just add `svg` to the list of things to be loaded as files:
```
            {
                test: /\.(ttf|eot|woff|png|glb|svg)$/,
                use: 'file-loader'
            },
```

**Comment by oyvindberg** [comment]
Like before feel free to merge your changes whenever you feel it's good enough @mvillafuertem 

Cookie points if you also remember to run `scalafmt` and `dist` :)

**Comment by mvillafuertem** [comment]
There is a problem with text input and I don't understand why.

**Comment by oyvindberg** [comment]
Yeah, you're `toString`ing a DOM element. There is an irritation with the TextField component where it can be implemented behind the scenes as three different DOM elements depending on props.
For that reason we get this prop:
```
def onChange(value: ChangeEvent[HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement] => Unit)
```
This is ok enough to use in typescript, but in Scala.js we'll just have to cast somehow

I guess you have two choices:
```
.set("onChange", (e: ChangeEvent[HTMLInputElement]) => setLoginValue(e.currentTarget.value))
// or 
.onChange(e => setLoginValue(e.currentTarget.asInstanceOf[HTMLInputElement].value))`

**Comment by oyvindberg** [comment]
Note that the converter *could* generate `onChangeHTMLInputElement`, `onChangeHTMLTextAreaElement` which take a callback with the wanted parameter type. when it comes across similar things.

**Pull request merged**
