### PR TITLE
React native finalized

### PR DESCRIPTION
**Pull request by mcallisto**

### CODE REVIEW

**Comment by mcallisto** [comment]
Almost there, I have been able to open the app on Expo, but it freezes when trying to open the "Antd" page from the menu. No idea why. The "Home" and "React Router" pages are fine.

The only thing I noticed are 4 warnings at compile time:

```
[warn] .../SlinkyTypedDemos/react-native/target/scala-2.13/src_managed/main/tso/typingsSlinky/atAntDashDesignReactDashNative/atAntDashDesignReactDashNativeStrings.scala:168:16: Generated class typingsSlinky.atAntDashDesignReactDashNative.atAntDashDesignReactDashNativeStrings$empty differs only in case from typingsSlinky.atAntDashDesignReactDashNative.atAntDashDesignReactDashNativeStrings$Empty.
[warn]   Such classes will overwrite one another on case-insensitive filesystems.
[warn]   sealed trait empty extends js.Object
[warn]                ^
```

```
[warn] .../SlinkyTypedDemos/react-native/target/scala-2.13/src_managed/main/tso/typingsSlinky/atAntDashDesignReactDashNative/components/DatePicker.scala:19:8: Generated class typingsSlinky.atAntDashDesignReactDashNative.components.Datepicker$ differs only in case from typingsSlinky.atAntDashDesignReactDashNative.components.DatePicker$.
[warn]   Such classes will overwrite one another on case-insensitive filesystems.
[warn] object Datepicker
[warn]        ^
```

```
[warn] .../SlinkyTypedDemos/react-native/target/scala-2.13/src_managed/main/tso/typingsSlinky/atAntDashDesignReactDashNative/components/DatePicker.scala:23:19: Generated class typingsSlinky.atAntDashDesignReactDashNative.components.Datepicker$raw$ differs only in case from typingsSlinky.atAntDashDesignReactDashNative.components.DatePicker$raw$.
[warn]   Such classes will overwrite one another on case-insensitive filesystems.
[warn]   override object raw extends Raw {
[warn]                   ^
```

```
[warn] .../SlinkyTypedDemos/react-native/target/scala-2.13/src_managed/main/tso/typingsSlinky/atAntDashDesignReactDashNative/components/DatePicker.scala:26:12: Generated class typingsSlinky.atAntDashDesignReactDashNative.components.Datepicker$raw$componentImport$ differs only in case from typingsSlinky.atAntDashDesignReactDashNative.components.DatePicker$raw$componentImport$.
[warn]   Such classes will overwrite one another on case-insensitive filesystems.
[warn]     object componentImport extends js.Object
[warn]            ^
```

**Comment by oyvindberg** [comment]
Great! Seems unlikely that those would be at fault, even i you use that date picker I suppose both point to the same javascript component.

I remember I finally found debug console from react-native eventually last time I was looking at it, that included javascript errors and so on. Seem to remember i started a debug mode in androind studio. Otherwise you can start commenting out stuff and see if starts loading.

Tell me if youre stuck, I can have a look within some days

**Comment by oyvindberg** [comment]
By the way feel free to push all the commits to your first PR, I don't suppose there is much point in merging to my branch

**Comment by mcallisto** [comment]
Found, the culprits are `IconFill` and `IconOutline`.
Maybe due the `name` and `size` props now coming from `slinky.web.html`.

> By the way feel free to push all the commits to your first PR, I don't suppose there is much point in merging to my branch

Ok, once done I will push everything to #1.

**Comment by oyvindberg** [comment]
Ahaa! That does make some sense. 

So there is custom code to filter out dom props from component so users can use slinkys `:=` syntax instead, I guess the logical thing would be to just not do that for native components. Do you have any other ideas for things which should be different between native and web components for slinky?

**Comment by mcallisto** [comment]
> Ahaa! That does make some sense.
> 
> So there is custom code to filter out dom props from component so users can use slinkys `:=` syntax instead, I guess the logical thing would be to just not do that for native components.

Just to complete my findings, in one case it worked, see `InputItem()(placeholder := "input text")`, where `slinky.web.html.placeholder` correctly replaced (to my surprise, I have to say) the Antd Native prop. So I guess the automatic filter can work only if the libraries do some accurate naming. Maybe there should be the option to set or unset the filter depending on the library.

> Do you have any other ideas for things which should be different between native and web components for slinky?

So far no, but I have some doubts. For example the separate `bang88__react-native-drawer-layout` library, needed for the `Drawer` component, it's now by default tied to `ant-design__react-native`? And how? In the previous solution, I would declare in `build.sbt` if I needed it or not.

**Comment by oyvindberg** [comment]
Ok, so I had another go now.

> Just to complete my findings, in one case it worked, see InputItem()(placeholder := "input text"), where slinky.web.html.placeholder correctly replaced (to my surprise, I have to say) the Antd Native prop. So I guess the automatic filter can work only if the libraries do some accurate naming. Maybe there should be the option to set or unset the filter depending on the library.

So the mechanism of using `:=` works actually. It's not so surprising since it just sets fields on a javascript objects. What went wrong in that particular case is that the `size` prop had the wrong type (`String` instead of `Double`), and something along the way complained. I'm pretty sure this is a bug in slinky, `size` should have been a [`Double`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1809)

So about using this mechanism in the first place, I did it for two reasons:
- fit in with how slinky does things
- compile less code

The second is pretty significant, given that we can filter out 100+ parameters from many component props which include them.

We can remove this syntax altogether, or hide it between an sbt configuration. I'll leave it like it is for now, and we see if it causes more problems. Seems fine?

> So far no, but I have some doubts. For example the separate bang88__react-native-drawer-layout library, needed for the Drawer component, it's now by default tied to ant-design__react-native? And how? In the previous solution, I would declare in build.sbt if I needed it or not.

I haven't looked into it, but it is a transitive dependency somewhere, and it's referenced in code so it's automatically included. Are you sure you didnt have it on the classpath before even if you didnt specify?

**Comment by mcallisto** [comment]
> We can remove this syntax altogether, or hide it between an sbt configuration. I'll leave it like it is for now, and we see if it causes more problems. Seems fine?

I agree, I saw also the workaround, very good.

>  Are you sure you didnt have it on the classpath before even if you didnt specify?

If I remember correctly yes, it wasn't. But anyway is a minor issue.

**Pull request merged**
